# 'docker/install.yml'
---

- name: Downloading docker rpm package
  get_url:
    url: "{{docker_package_url}}"
    dest: "{{docker_install_dir}}"
    mode: 0644

- name: Install docker rpm
  command: rpm -ivh /docker/*.rpm

- name: Install docker-compose
  get_url:
    url: 
    dest: "{{docker_compose_dir}}"
    mode: 0755

