# 'docker/install.yml'
---
  
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: Downloading required package
  get_url:
    url: "{{ item }}"
    dest: "{{docker_download_dir}}"
    mode: 0644
  loop: "{{ docker_packages_url }}"

- name: Installing Dependencies
  command: "yum install -y {{ item }}"
  args:
    chdir: /download
  loop: "{{ docker_packages }}"

- name: Install docker-compose
  get_url:
    url: "{{ docker_compose_url}}"
    dest: "{{docker_compose_dir}}"
    mode: 0755
