---

- name: Set linux user account password for 'postgres' user
  command: "echo '{{ postgres_config_owner }}:{{postgres_config_owner_password }}' | chpasswd"

- name: Initialise the database
  command: "postgresql-setup initdb"

- name: Move datbase location
  command: "rsync -av /var/lib/pgsql/ {{ postgres_config_dbhome }} && rm -fr /var/lib/pgsql/"

- name: Ensure database configuration file present
  file:
    path: "{{ postgres_config_dbhome }}/data/postgresql.conf"
    state: "present"
    mode: "0600"
    owner: "{{ postgres_config_owner }}"
    group: "{{ postgres_config_group }}"

- name: patch configuration file
  lineinfile:
    path: "{{ postgres_config_dbhome}}/data/postgresql.conf"
    regexp: "data.directory ="
    line: "data.directory = '{{ postgres_config_dbhome}}/data'"

- name: patch configuration file
  lineinfile:
    path: "{{ postgres_config_dbhome}}/data/postgresql.conf"
    regexp: "hba_file ="
    line: "hba_file = '{{ postgres_config_dbhome}}/data/pg_hba.conf'"

- name: patch configuration file
  lineinfile:
    path: "{{ postgres_config_dbhome}}/data/postgresql.conf"
    regexp: "indent_file ="
    line: "indent_file = '{{ postgres_config_dbhome}}/data/pg_indent.conf'"

- name: patch configuration file
  lineinfile:
    path: "{{ postgres_config_dbhome}}/data/postgresql.conf"
    regexp: "listen_addresses ="
    line: "listen_addresses = {{ postgres_config_dbhost }}"

- name: patch configuration file
  lineinfile:
    path: "{{ postgres_config_dbhome}}/data/postgresql.conf"
    regexp: "port ="
    line: "port = {{ postgres_config_dbport }}"

- name: Ensure database configuration file present 'pg_hba'
  file:
    path: "{{ postgres_config_dbhome }}/data/pg_hba.conf"
    state: "present"
    mode: "0600"
    owner: "{{ postgres_config_owner }}"
    group: "{{ postgres_config_group }}"

- name: patch configuration file
  lineinfile:
    path: "{{ postgres_config_dbhome}}/data/pg_hba.conf"
    regexp: "local[\s\t]+all[\s\t]+all"
    line: "local\tall\t\tall\t\t\t\t\ttrust"

- name: patch configuration file
  lineinfile:
    path: "{{ postgres_config_dbhome}}/data/pg_hba.conf"
    regexp: "host[\s\t]+all[\s\t]+all[\s\t]+127.0.0.1/32"
    line: "host\tall\t\tall\t\t127.0.0.1/32\t\ttrust"

- name: patch configuration file
  lineinfile:
    path: "{{ postgres_config_dbhome}}/data/pg_hba.conf"
    regexp: "host[\s\t]+all[\s\t]+all[\s\t]+::1/128"
    line: "host\tall\t\tall\t\t::1/128\t\t\ttrust"

- name: Ensure database configuration file present 'pg_ident'
  file:
    path: "{{ postgres_config_dbhome }}/data/pg_ident.conf"
    state: "present"
    mode: "0600"
    owner: "{{ postgres_config_owner }}"
    group: "{{ postgres_config_group }}"

- name: Ensure postgresql.service file present
  file:
    path: "/usr/lib/systemd/system/postgresql.service"
    state: "present"
    mode: "0644"

- name: patch Service file
  lineinfile:
    path: "/usr/lib/systemd/system/postgresql.service"
    regexp: "Environment=PGDATA"
    line: "Environment=PGDATA={{ postgres_config_dbhome }}/data""
