---
# tasks file for xl_release

- name: Setup Directories and User/Group for Installation of xl-release
  include_tasks: setup.yml

- name: Installing xl-release Package
  include_tasks: install.yml

- name: Configure xl-release Installation
  include_tasks: config.yml
